Assignment 7.1 : Classifications and Regression

Name:	Reyes, Paula Nicole G.

Section:	CPE32S1

Date Performed:	06/30/2024

Date Submitted:	06/30/2024

Instructor:	Engr. Roman Richard

In [1]:
!pip install scikeras

In [2]:
!pip install np_utils

# Importing the libraries

In [4]:
import numpy as np
import pandas as pd
from keras.models import Sequential
from keras.layers import Dense
from scikeras.wrappers import KerasClassifier
from scikeras.wrappers import KerasRegressor
from keras.utils import to_categorical
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline

Medical Cost Personal Datasets (MCPD) generally encompass data related to healthcare expenses and associated personal information. These datasets are essential for examining and comprehending healthcare spending, insurance claims, and the financial impact on patients.







In [17]:
#reading the csv file
df = pd.read_csv('/content/insurance.csv')
df.head()

age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [18]:
#changing the string values into numerical values using lambda
df["sex"] = df["sex"].apply(lambda toLabel:0 if toLabel == 'Male' else 1)
df["children"] = df["children"].apply(lambda toLabel:0 if toLabel == 'no' else 1)
df["smoker"] = df["smoker"].apply(lambda toLabel:0 if toLabel == 'no' else 1)
df.head()

age  sex     bmi  children  smoker     region      charges
0   19    1  27.900         1       1  southwest  16884.92400
1   18    1  33.770         1       0  southeast   1725.55230
2   28    1  33.000         1       0  southeast   4449.46200
3   33    1  22.705         1       0  northwest  21984.47061
4   32    1  28.880         1       0  northwest   3866.85520

In [19]:
#changing the string values into categorical types
df['region'] = df['region'].astype('category')
df['region'] = df['region'].cat.codes

df.head()

age  sex     bmi  children  smoker  region      charges
0   19    1  27.900         1       1       3  16884.92400
1   18    1  33.770         1       0       2   1725.55230
2   28    1  33.000         1       0       2   4449.46200
3   33    1  22.705         1       0       1  21984.47061
4   32    1  28.880         1       0       1   3866.85520

In [55]:
#splitting the input values into output values
#X = all input values
#Y = output value
dataset = df.values
X = dataset[:,0:4]
Y = dataset[:,4]

In [56]:
#printing the values in array form
X

array([[19.  ,  1.  , 27.9 ,  0.  ],
       [18.  ,  0.  , 33.77,  1.  ],
       [28.  ,  0.  , 33.  ,  3.  ],
       ...,
       [18.  ,  1.  , 36.85,  0.  ],
       [21.  ,  1.  , 25.8 ,  0.  ],
       [61.  ,  1.  , 29.07,  0.  ]])

In [57]:
#printing all the output values per row
Y

array([1., 0., 0., ..., 0., 0., 1.])

In [58]:
#one-hot coded variables
#encode class values as integers
encoder = LabelEncoder()
encoder.fit(Y)
encoded_Y = encoder.transform(Y)
#convert integers to dummy variables
dummy_y = to_categorical(encoded_Y)

In [59]:
# define baseline model
def baseline_model():
# create model
  model = Sequential()
  model.add(Dense(4, input_shape=(16,), activation='relu'))
  model.add(Dense(7, activation='sigmoid'))
# Compile model
  model.compile(loss='categorical_crossentropy' , optimizer= 'adam' , metrics=[ 'accuracy' ])
  return model

In [60]:
#one-hot coded variables
#encode class values as integers
encoder = LabelEncoder()
encoder.fit(Y)
encoded_Y = encoder.transform(Y)
#convert integers to dummy variables
dummy_y = to_categorical(encoded_Y)

In [61]:
# Define the model
def create_baseline():
    model = Sequential()
    model.add(Dense(16, input_shape=(4,), activation='relu'))
    model.add(Dense(16, activation='relu'))
    model.add(Dense(3, activation='softmax'))
    model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
    return model

In [63]:
estimator = KerasClassifier(model=create_baseline, epochs=200, batch_size=5, verbose=0)

# Regression Dataset

In [33]:

#reading the csv file
df = pd.read_csv('/content/insurance.csv')
df.head()

age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [34]:
#changing the string values into numerical values using lambda
df["sex"] = df["sex"].apply(lambda toLabel:0 if toLabel == 'male' else 1)
df["smoker"] = df["smoker"].apply(lambda toLabel:0 if toLabel == 'no' else 1)
df["region"] = df["region"].apply(lambda toLabel:0 if toLabel == 'northwest' else 1)
df.head()

age  sex     bmi  children  smoker  region      charges
0   19    1  27.900         0       1       1  16884.92400
1   18    0  33.770         1       0       1   1725.55230
2   28    0  33.000         3       0       1   4449.46200
3   33    0  22.705         0       0       0  21984.47061
4   32    0  28.880         0       0       0   3866.85520

In [35]:
#splitting the input values into output values
#X = all input values
#Y = output value
dataset = df.values
X = dataset[:,0:6]
Y = dataset[:,6]

In [36]:

#printing the values in array form
X

array([[19.  ,  1.  , 27.9 ,  0.  ,  1.  ,  1.  ],
       [18.  ,  0.  , 33.77,  1.  ,  0.  ,  1.  ],
       [28.  ,  0.  , 33.  ,  3.  ,  0.  ,  1.  ],
       ...,
       [18.  ,  1.  , 36.85,  0.  ,  0.  ,  1.  ],
       [21.  ,  1.  , 25.8 ,  0.  ,  0.  ,  1.  ],
       [61.  ,  1.  , 29.07,  0.  ,  1.  ,  0.  ]])

In [42]:
#printing all the output values per row
Y

array([16884.924 ,  1725.5523,  4449.462 , ...,  1629.8335,  2007.945 ,
       29141.3603])

In [38]:

# define base model
def baseline_model():
	# create model
  model = Sequential()
  model.add(Dense(6, input_shape=(6,), kernel_initializer='normal', activation='relu'))
  model.add(Dense(1, kernel_initializer='normal'))
	# Compile model
  model.compile(loss='mean_squared_error', optimizer='adam')
  return model

#training the model
estimator = KerasRegressor(model=baseline_model, epochs=100, batch_size=5, verbose=0)
#evaluating the model using k-fold cross validation in regression
kfold = KFold(n_splits=10)
results = cross_val_score(estimator, X, Y, cv=kfold, scoring='neg_mean_squared_error')
print("Baseline: %.2f (%.2f) MSE" % (results.mean(), results.std()))

/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
/usr/lo

Baseline: -127802558.86 (15259287.06) MSE


# Define Base Model

In [39]:

# define base model
def baseline_model():
	# create model
  model = Sequential()
  model.add(Dense(6, input_shape=(6,), kernel_initializer='normal', activation='relu'))
  model.add(Dense(1, kernel_initializer='normal'))
	# Compile model
  model.compile(loss='mean_squared_error', optimizer='adam')
  return model

#standardizing the model
estimators = []
estimators.append(('standardize', StandardScaler()))
#training the model
estimators.append(('mlp', KerasRegressor(model=baseline_model, epochs=50, batch_size=5, verbose=0)))
pipeline = Pipeline(estimators)
#evaluating the model using k-fold cross validation in regression
kfold = KFold(n_splits=10)
results = cross_val_score(pipeline, X, Y, cv=kfold, scoring='neg_mean_squared_error')
print("Standardized: %.2f (%.2f) MSE" % (results.mean(), results.std()))

/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
/usr/lo

Standardized: -286473902.07 (30428393.33) MSE


# Deeper Network

In [40]:
#define base model (deeper network)
def baseline_model():
	#create model
  model = Sequential()
  model.add(Dense(6, input_shape=(6,), kernel_initializer='normal', activation='relu'))
  model.add(Dense(3, kernel_initializer='normal', activation='relu'))
  model.add(Dense(1, kernel_initializer='normal'))
	#Compile model
  model.compile(loss='mean_squared_error', optimizer='adam')
  return model

#standardizing the model
estimators = []
estimators.append(('standardize', StandardScaler()))
#training the model
estimators.append(('mlp', KerasRegressor(model=baseline_model, epochs=50, batch_size=5, verbose=0)))
pipeline = Pipeline(estimators)
#evaluating the model using k-fold cross validation in regression
kfold = KFold(n_splits=10)
results = cross_val_score(pipeline, X, Y, cv=kfold, scoring='neg_mean_squared_error')
print("Standardized: %.2f (%.2f) MSE" % (results.mean(), results.std()))

/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
/usr/lo

Standardized: -43396047.52 (7045624.49) MSE


# Smaller Neurons

In [41]:
#define base model (smaller neurons)
def baseline_model():
	# create model
  model = Sequential()
  model.add(Dense(3, input_shape=(6,), kernel_initializer='normal', activation='relu'))
  model.add(Dense(1, kernel_initializer='normal'))
	# Compile model
  model.compile(loss='mean_squared_error', optimizer='adam')
  return model

#standardizing the model
estimators = []
estimators.append(('standardize', StandardScaler()))
#training the model
estimators.append(('mlp', KerasRegressor(model=baseline_model, epochs=50, batch_size=5, verbose=0)))
pipeline = Pipeline(estimators)
#evaluating the model using k-fold cross validation in regression
kfold = KFold(n_splits=10)
results = cross_val_score(pipeline, X, Y, cv=kfold, scoring='neg_mean_squared_error')
print("Standardized: %.2f (%.2f) MSE" % (results.mean(), results.std()))

/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
/usr/lo

Standardized: -306217626.15 (33538794.06) MSE


# Larger Neurons

In [43]:
# define base model (larger neurons)
def baseline_model():
	# create model
  model = Sequential()
  model.add(Dense(12, input_shape=(6,), kernel_initializer='normal', activation='relu'))
  model.add(Dense(1, kernel_initializer='normal'))
	# Compile model
  model.compile(loss='mean_squared_error', optimizer='adam')
  return model

#standardizing the model
estimators = []
estimators.append(('standardize', StandardScaler()))
#training the model
estimators.append(('mlp', KerasRegressor(model=baseline_model, epochs=50, batch_size=5, verbose=0)))
pipeline = Pipeline(estimators)
#evaluating the model using k-fold cross validation in regression
kfold = KFold(n_splits=10)
results = cross_val_score(pipeline, X, Y, cv=kfold, scoring='neg_mean_squared_error')
print("Standardized: %.2f (%.2f) MSE" % (results.mean(), results.std()))

/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
/usr/lo

Standardized: -252179139.98 (26843970.43) MSE


# Conclusion

K-fold cross-validation must be used to evaluate the performance of the basic model before attempting to develop a classification model. To improve the model's accuracy and fortify its ability to spot intricate patterns and correlations in the data, more hidden layers can be added. By following these steps, a classification model that more accurately predicts and categorizes data based on the given attributes can be created.

Regression analysis should be performed as follows: first, create a baseline model to use as a point of comparison; second, standardize the dataset to ensure that each feature contributes equally to the model's performance; and third, explore layer and neuron tuning by evaluating both smaller and larger network configurations. These stages work to improve the architecture and data pretreatment techniques in order to boost the accuracy and efficiency of the regression model.
